- docs/content-data-structure.md
- src/content/examples/a-markdown-page.md
Initial documentation is added around how to explore the site's data
and content using GraphQL. The example markdown page has been expanded
to include more examples.
As we move forwards with this we alwso need to consider more complex
requirements including custom components and image embedding. The ways
in which we decide to meet these requirements will influence how we
structure the markdown files as time goes on.
>  Add documentation around content data structure

- gatsby-config.js
- package.json
- src/components/ContentSection.tsx
- src/components/HeroBox.tsx
- src/content/a-markdown-page.mdx
- src/templates/page.tsx
- yarn.lock
__Note: This needs merging _after_ https://github.com/guardian/guardian-engineering-site/pull/9__
This makes the process of adding a content section more concise and allows an image URL to be passed to the component for rendering in the `HeroImage` child component.
This also adds the ability to add inline markdown of images to the ordinary `.mdx` files.
There's still work to do here around making the `ContentSection` more general - at the moment the text of the `Content` component is hardcoded in. This ideally needs to be made part of the mdx file in some way so that it can be queried by GraphQL and added in from there.
> Add Images to Content Section Hero

- .github/workflows/cd.yml
- .github/workflows/ci.yml
Uses `yarn` instead of `npm` to run gh-actions. This makes sure that we're using the same tooling in development as in CI and CD.
You can [download `nektos/act`](https://github.com/nektos/act) to run gh-actions on local machines. You then run `act pull_request` to test the CI step. The CD step only uses `yarn` to run the CI step, meaning that testing CI tests CD, removing the risk of pushing a broken build to the `gh-pages` branch.
> Swap to yarn in gh-actions

- .github/workflows/cd.yml
Uses `main` branch for deployment in `gh-actions`
> Swap from master to main

- src/components/Nav.astro
- src/pages/open-people.astro
- src/pages/open-source.astro
I found the navigation for "open people" and "open source" confusing as it would jump to sections within the same page and lose the navigation, whereas the other nav items link to separate pages.
This PR (assuming its okay to change the structure) splits the sections into separate pages.
Before:
After:
> Split "open" pages

- package.json
- pnpm-lock.yaml
- public/CNAME
- Bump @astrojs/renderer-react from 0.3.1 to 0.4.0
- bump vite
- remove preact renderer
> Bump dependencies (2021-01-07)

- src/components/BlogFeed.astro
* adds a link to see all posts on the Engineering blog
> Add link to the Engineering blog

- astro.config.mjs
#149 removed `@astrojs/renderer-preact` as a dependency, and so it needs to be removed from the Astro configuration too. `@astrojs/renderer-preact` is a dependency of `astro`, which is why the build was still working.
> Remove @astrojs/renderer-preact from config

- package.json
- pnpm-lock.yaml
Downgrade Astro back to `0.21.12`, to fix an emotion bug.
Visit the live website: [theguardian.engineering](https://theguardian.engineering/)
Beautiful icons.
> Downgrade Astro to fix emotion rendering bug

- .github/renovate.json
Don’t bump dependencies in Gatsby: it’s a legacy project.
Look at the Renovate updates.
No more PRs like #158, which bump deps in the `gatsby` folder
The Gatsby project is there as an archive, it’s not meant to be run.
> Stop bumping dependencies for Gatsby

- src/components/Nav.astro
- src/pages/events.md
* Remove events tab from the main nav due to insufficient content
* Adds some recent events to the events source file
> Remove events from nav bar, add recent events

- src/pages/open-source.astro
This PR adds more information about the department's ethos of developing in the open (linking to [Robert Rees' engineering blog post on the subject](https://www.theguardian.com/info/developer-blog/2014/nov/28/developing-in-the-open)), as well filling out the lists of languages, frameworks, and tools we use.
Any suggestions on other good languages/frameworks/tools to include are very welcome.
> Fill out Open Source page

- src/pages/index.astro
This is subjective so completely for your consideration.
I felt that the number badges are not adding much to the UX so this PR removes them.
Before:
After:
> Remove number badges from 'cause' cards

- src/pages/index.astro
I noticed that the space between headers and text on homepage cards in `index.astro` wasn't consistent (see the 'Coding in the open' one below). It looks like having one of the cards in Markdown and the others in HTML was causing a discrepancy in spacing. This PR makes the four of them consistent by making them all HTML. I know Markdown is a bit cleaner but an `<a>` element seems harmless enough here.
Before
After
> Fix homepage card spacing issue

- src/pages/index.astro
Small PR to add riveting alt text to the new homepage image. This Improves accessibility, bumps up the Lighthouse rating from 82 to 100, and gives SEO a little boost too. A meta description is needed for a perfect SEO score but I figured that's something for another PR. 
Before 
After
> Add alt text to homepage image

- .env
- .github/workflows/cd.yml
- .gitignore
- src/components/BlogFeed.astro
- src/env.d.ts
The API key used to fetch content from CAPI is currently hardcoded with the `test` key. This means that the results for the blog feed are out of date.
This change loads the API key for CAPI from the `CAPI_KEY` environment variable, with a fallback value of `test`.
> refactor: Load CAPI API key from environment

- src/components/Bubbles.svelte
- src/layouts/page.astro
With a `fixed` position, the bubbles are all packed together at the top of the page on the first load. Using an `absolute` position fixes this issue, on my local device.
> fix(bubbles): initial load state on iOS

- src/components/BlogFeed.astro
As we've upgraded our `astro` version, we can remove the workaround for loading environment variables. The bug was fixed in https://github.com/withastro/astro/pull/3327
* Check that the deployed & local environments load values correctly
> Remove environment variables workaround

- src/pages/open-source.astro
- Uses the `pushed_at` field which better represents when code was changed in the repository
- the previous field, `updated_at`, indicates when the repository object was changed. This includes things like the description, wiki pages or primary language. [This StackOverflow post](https://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at) has more details
- Fixes the "updated at" display in the list of recently updated repositories. `repo.pushed_at` is an `ISO 8601` string, so we can create a `new Date(pushed_at)` and call `getTime()`
| Before | After |
| - | - |
| <img width="703" alt="Screenshot 2022-08-10 at 11 55 31" src="https://user-images.githubusercontent.com/705427/183884677-23539a60-5ef4-41ee-9c1b-c7915bbbff14.png"> | <img …
> fix: recently updated repositories "updated at" display

- src/components/Bubbles.svelte
Ensure that the aside layer is takin the full width
Run locally.
Prettier bubbles that get out the way on desktop.
N/A
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [X] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [X] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [X] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> fix: bubbles where cropped on large viewports

- .vscode/settings.json
- src/pages/diversity.astro
- src/pages/index.astro
- src/pages/open-source.astro
async getHeaders is deprecated- refactor(diversity): use getHeadings method
- feat(formatter): use Astro plugin
- chore: remove unused import
- feat(timeAgo): absolute dates
`pnpm dev`
Resolves #190 
N/A
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [X] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [X] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [X] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)
> refactor(diversity): use getHeadings method

- package.json
Add package name and version: `guardian-engineering-site@1.0.0`
It’s right there.
This is what `package.json` expects
N/A
> fix: add name and version to package.json

- src/pages/progression.astro
- Adds padding to markdown sections on the [Progression page](https://theguardian.engineering/progression)
| Before | After |
|--------|-------|
|    ![before](https://user-images.githubusercontent.com/705427/214567719-e643ca79-32ff-4afd-95a0-d597b1c163c3.png)    |     ![after](https://user-images.githubusercontent.com/705427/214567755-f05feeed-647e-4ae5-8675-f5f248c81346.png)  |
> fix padding on progression page

- src/components/Nav.astro
- Sets the nav bar to `overflow: auto` from `overflow: scroll`. With `overflow: scroll`, Firefox displays the scroll bars when not needed which looks odd!
| | |
|--------| -- |
| Before |  ![before]     |
| After | ![after]  |
[after]: https://user-images.githubusercontent.com/705427/197163042-cda71b9b-af4e-465a-93e5-6a95c68a1383.png
[before]: https://user-images.githubusercontent.com/705427/197163049-1daca085-04c8-45b9-a422-8cfa053963fc.png
> fix(nav): nav should `overflow: auto`

- package.json
- pnpm-lock.yaml
- src/components/BlogFeed.astro
- tsconfig.json
Start parsing the responses from CAPI and DCR
`pnpm build` works with an “internal” API key.
A [recently updated article](https://www.theguardian.com/info/2018/may/02/the-digital-fellowship-is-your-foot-in-the-door-to-the-future-of-news) [caused failures in our Continuous Deployment](https://github.com/guardian/guardian-engineering-site/actions/workflows/cd.yml) process because it did not have an image.
**[CD works](https://github.com/guardian/guardian-engineering-site/actions/runs/7821077736/job/21337254416)**!
We’ll get errors at the fetch boundary, rather than deeply nested in our code.
> Parse CAPI & DCR responses

- src/components/Nav.astro
- src/layouts/page.astro
Add ViewTransitions
Improves nav bar UI
A smoother feel. See video below
[Before](https://github.com/guardian/guardian-engineering-site/assets/9574885/ce04d587-2879-40be-9fb8-5ac6d2f728e6)
[After](https://github.com/guardian/guardian-engineering-site/assets/9574885/3be3969d-45d5-4449-b8cf-6b3238167765)
-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey …
> Add View Transitions

- src/pages/index.astro
Uses Astro's [Image component](https://docs.astro.build/en/guides/images/#image--astroassets) for the main image on the homepage
The Image component displays an optimised version of the image. For example, it will use webp where available.
| Before | After |
| - | - |
| ![b1] | ![a1] |
| ![b2] | ![a2] |
| ![b3] | ![a3] |
[b1]: https://github.com/guardian/guardian-engineering-site/assets/9574885/085aa909-eee0-4ee0-8448-f7abdd280686
[a1]: https://github.com/guardian/guardian-engineering-site/assets/9574885/a8bfb8b4-f16c-4cc9-ab4f-5c3442c2adb1
[b2]: https://github.com/guardian/guardian-engineering-site/assets/9574885/c2d41251-cf12-45d5-a41f-c65434bded7d
[a2]: https://github.com/guardian/guardian-engineering-site/assets/9574885/48d56504-cea8-4b53-b2c4-480d685fe3b5
[b3]: …
> Use Astro Image to optimise main image on homepage

- package.json
- pnpm-lock.yaml
- src/components/BlogFeed.astro
- src/components/Nav.astro
- src/components/blog/Header.astro
- src/layouts/blog.astro
- src/layouts/blog/Base.astro
- src/pages/blog.astro
- src/pages/blog/rss.xml.js
- Adds a basic RSS Feed using [`@astrojs/rss`](https://docs.astro.build/en/recipes/rss/), which will be available at https://theguardian.engineering/blog/rss.xml
- Updates capitalisation on the `title`
- Adds `meta` `description` for SEO purposes
- Checkout the branch locally, run development mode, and open the feed, potentially check with a rss feed reader/validator
The `@astrojs/rss` plugin only supports RSS 2.0, we may want to support Atom feeds instead, as [Atom](https://en.wikipedia.org/wiki/Atom_(web_standard)) feeds are better defined.
@emdash-ie mentioned that it would also be useful to have the `content` included in the feed too, however the plugin doesn't interface with the built in rendering methods in Astro, and instead we have to rely on using an markdown processing package. …
> Blog | Add RSS Feed and meta description to blog pages

- src/pages/blog/rss.xml.js
In https://github.com/guardian/guardian-engineering-site/pull/239 we added an RSS feed available through https://theguardian.engineering/blog/rss.xml
However after deploying we noticed that the links wouldn't work
This is because the RSS feed plugin trailing slashes are applied by default, we have to remove them in order to get the links working with our project https://docs.astro.build/en/recipes/rss/#removing-trailing-slashes
This PR does that
> Fix | Blog | Remove trailing slash on rss feed
